server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html/frontend;
    index  index.html index.htm;

    location = /healthz {
        default_type text/plain;
        return 200 'ok';
    }

    location ~* \.wav$ {
        default_type audio/wav;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html/frontend;
    }
}
